POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Teste",
    "email": "teste@gmail.com",
    "password": "1234567oito"
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "password": "1234567oito"
}

###

GET http://localhost:3000/users/1
Authorization: Bearer seu_token

###

PATCH http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer seu_token

{
    "name": "Breno Martins da Silva"
}

###

DELETE http://localhost:3000/users/1
Authorization: Bearer seu_token

###

POST http://localhost:3000/questions
Content-Type: application/json
Authorization: Bearer seu_token

{
    "title": "Minha primeira questão",
    "body": "Minha primeira questão no fórum"
}

###

GET http://localhost:3000/questions
Authorization: Bearer seu_token

###

GET http://localhost:3000/questions/1
Authorization: Bearer seu_token

###

PATCH http://localhost:3000/questions/1
Content-Type: application/json
Authorization: Bearer seu_token

{
    "title": "Minha primeira questão no fórum"
}

###

DELETE http://localhost:3000/questions/1
Authorization: Bearer seu_token

###

POST http://localhost:3000/answers/1
Content-Type: application/json
Authorization: Bearer seu_token

{
    "body": "Minha primeira resposta"
}

###

GET http://localhost:3000/answers
Authorization: Bearer seu_token

###

GET http://localhost:3000/answers/1
Authorization: Bearer seu_token

###

PATCH http://localhost:3000/answers/1
Content-Type: application/json
Authorization: Bearer seu_token

{
    "body": "Minha primeira resposta no fórum"
}

###

DELETE http://localhost:3000/answers/1
Authorization: Bearer seu_token