POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Breno M. Silva",
    "email": "sbrenomartins@gmail.com",
    "password": "1234567oito"
}

###

GET http://localhost:3000/users/3

###

PATCH http://localhost:3000/users/3
Content-Type: application/json

{
    "name": "Breno Martins da Silva"
}

###

DELETE http://localhost:3000/users/2

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "sbrenomartins@gmail.com",
    "password": "1234567oito"
}